# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular lyrics across whole site', primary_key=True, serialize=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(help_text='Enter a comment', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TrackComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular lyrics across whole site', primary_key=True, serialize=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(help_text='Enter a comment', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='lyrics',
            name='track',
        ),
        migrations.AddField(
            model_name='artist',
            name='number_following',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='number_of_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='propic',
            field=models.FileField(default='user_propics/profile_default.png', upload_to='user_propics/'),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Artist'),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this track', to='spitfire.Genre'),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='text',
            field=models.TextField(default='Lyrical spiritual lyrics!', help_text='Enter lyrics', max_length=1000),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Lyrics'),
        ),
        migrations.AddField(
            model_name='track',
            name='mp3',
            field=models.FileField(default='user_audio/track_default.mp3', upload_to='user_audio/'),
        ),
        migrations.AddField(
            model_name='track',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular artist across whole site', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular lyrics across whole site', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular track across whole site', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trackcomment',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Artist'),
        ),
        migrations.AddField(
            model_name='trackcomment',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Track'),
        ),
        migrations.AddField(
            model_name='lyriccomment',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Artist'),
        ),
        migrations.AddField(
            model_name='lyriccomment',
            name='lyrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Lyrics'),
        ),
    ]
