# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular lyrics across whole site', primary_key=True, serialize=False)),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_set', to='spitfire.Artist')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_follow_set', to='spitfire.Artist')),
            ],
        ),
    ]
