# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0003_artist_homeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spits',
            field=models.CharField(default='', max_length=100),
        ),
    ]
