# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0004_artist_spits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='lyrics',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Track'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='homeAddress',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spits',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
