# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0005_auto_20171023_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='homeAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spits',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
