# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0008_auto_20171024_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='LyricComment',
        ),
        migrations.AddField(
            model_name='lyriccomment',
            name='lyrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Lyrics'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='Track',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Track'),
        ),
    ]
