# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0011_track_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='discription',
            new_name='description',
        ),
    ]
