# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0014_auto_20171026_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='../static/media'),
        ),
    ]
