# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0016_auto_20171026_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('sponsor_description', models.CharField(max_length=2000)),
            ],
        ),
    ]
