# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0017_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='Track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spitfire.Track'),
        ),
    ]
