# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0018_auto_20171030_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='homeAddress',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='number_following',
            new_name='number_of_following',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='spits',
            new_name='number_of_spits',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
