# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0021_auto_20171108_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(default='Firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(default='Lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='spitfire.User'),
        ),
    ]
