# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0027_auto_20171112_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
