# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0028_auto_20171112_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, upload_to='songs'),
        ),
    ]
