# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0029_track_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='file',
        ),
        migrations.AlterField(
            model_name='track',
            name='mp3',
            field=models.FileField(blank=True, upload_to='user_audio/'),
        ),
    ]
