# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0030_auto_20171118_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(default='static/user_propics/profile_default.png', upload_to='user_propics/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='mp3',
            field=models.FileField(default='static/user_audio/track_default.png', upload_to='user_audio/'),
        ),
    ]
