# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0031_auto_20171127_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=models.FileField(default='sponsor/sponsor_default.png', upload_to='sponsor/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(default='user_propics/profile_default.png', upload_to='user_propics/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='number_of_spits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='soundcloud_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lyriccomment',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Artist'),
        ),
        migrations.AlterField(
            model_name='lyriccomment',
            name='lyrics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Lyrics'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='Track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Track'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Artist'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='title',
            field=models.CharField(default='Some Terrific Lyrics', max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='mp3',
            field=models.FileField(default='user_audio/track_default.mp3', upload_to='user_audio/'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Artist'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Track'),
        ),
    ]
