# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0033_auto_20171128_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcomment',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spitfire.Artist'),
        ),
    ]
