# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0034_trackcomment_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcomment',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spitfire.Track'),
        ),
    ]
