# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0037_auto_20171128_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='soundcloud_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Artist'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Track'),
        ),
    ]
