# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0038_auto_20171128_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=models.FileField(default='sponsor/sponsor_default.png', upload_to='sponsor/'),
        ),
    ]
