# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0039_sponsor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
