# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0040_track_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.FileField(default='sponsor/sponsor_default.png', upload_to='sponsor/')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spitfire.Artist')),
            ],
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
