# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0041_auto_20171128_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.FileField(default='track_pics/trackpic_default.jpg', upload_to='track_pics/'),
        ),
    ]
