# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spitfire', '0042_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
